# Generated by Django 3.1.1 on 2020-10-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='image',
        ),
    ]
