# Generated by Django 3.1.1 on 2020-10-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0003_auto_20201023_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
