# Generated by Django 3.1.1 on 2020-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0005_auto_20201023_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='arrival_date',
            field=models.DateField(),
        ),
    ]
