# Generated by Django 3.1.1 on 2020-10-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0006_auto_20201024_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='arrival_date',
            field=models.CharField(max_length=10),
        ),
    ]
