# Generated by Django 3.1.1 on 2020-10-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0013_auto_20201026_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, default='/static/img/logo.jpg', null=True, upload_to='images/'),
        ),
    ]
