# Generated by Django 3.1.1 on 2020-10-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0014_auto_20201026_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, default='/images/logo.jpg', null=True, upload_to='images/'),
        ),
    ]
