# Generated by Django 3.1.1 on 2020-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0015_auto_20201027_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
