# Generated by Django 3.1.1 on 2020-10-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0016_auto_20201027_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('arrival_date',)},
        ),
    ]
