# Generated by Django 3.1.1 on 2020-10-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0019_auto_20201027_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'get_latest_by': ['-priority', 'arrival_date']},
        ),
    ]
