# Generated by Django 3.1.1 on 2020-10-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0020_auto_20201027_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='arrival_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
