# Generated by Django 3.1.1 on 2020-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0021_auto_20201028_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
