# Generated by Django 3.1.1 on 2020-10-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0022_auto_20201028_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'get_latest_by': ['arrival_date']},
        ),
    ]
