# Generated by Django 3.1.1 on 2020-10-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0023_auto_20201028_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'get_latest_by': ['updated_on']},
        ),
        migrations.AlterField(
            model_name='items',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
