# Generated by Django 3.1.1 on 2020-10-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0025_auto_20201028_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'get_latest_by': ['updated_on']},
        ),
    ]
