# Generated by Django 3.1.1 on 2020-10-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0026_auto_20201028_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-arrival_date']},
        ),
        migrations.AlterField(
            model_name='items',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
