# Generated by Django 3.1.1 on 2020-10-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0028_auto_20201028_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
