# Generated by Django 3.1.1 on 2020-10-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0030_auto_20201028_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
