# Generated by Django 3.1.1 on 2020-12-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0033_auto_20201210_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='/images/logo.jpg', null=True, upload_to='images/')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaelectric.items')),
            ],
        ),
    ]
