# Generated by Django 3.1.1 on 2021-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0034_itemsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
