# Generated by Django 3.1.1 on 2021-02-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0037_auto_20210208_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
