# Generated by Django 3.1.1 on 2021-02-08 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0038_auto_20210208_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'", regex='^\\+?0?\\d{9,13}$')]),
        ),
    ]
