# Generated by Django 3.1.1 on 2021-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaelectric', '0039_auto_20210208_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
